#! /bin/sh

. `dirname $0`/defaults
# echo GROOVE_CLASS_DIR: ${GROOVE_CLASS_DIR}
mkdir -p ${GROOVE_CLASS_DIR}
${JAVA_HOME}/bin/javac \
    -source 1.5 \
    -sourcepath . \
    -d ${GROOVE_CLASS_DIR} \
    -extdirs ${GROOVE_JAR_DIR} \
    -classpath ${GROOVE_CLASS_DIR} \
    $*
touch ${GROOVE_CLASS_DIR}
