//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.25 at 01:59:43 AM CEST 
//


package de.gupro.gxl.gxl_1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for graphType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="graphType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gupro.de/GXL/gxl-1.0.dtd}TypedElementType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.gupro.de/GXL/gxl-1.0.dtd}node"/>
 *         &lt;element ref="{http://www.gupro.de/GXL/gxl-1.0.dtd}edge"/>
 *         &lt;element ref="{http://www.gupro.de/GXL/gxl-1.0.dtd}rel"/>
 *       &lt;/choice>
 *       &lt;attribute name="role" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="edgeids" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="hypergraph" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="edgemode" type="{http://www.gupro.de/GXL/gxl-1.0.dtd}edgemodeType" default="directed" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "graphType", propOrder = {
    "nodeOrEdgeOrRel"
})
public class GraphType
    extends TypedElementType
{

    @XmlElements({
        @XmlElement(name = "rel", type = RelType.class),
        @XmlElement(name = "node", type = NodeType.class),
        @XmlElement(name = "edge", type = EdgeType.class)
    })
    protected List<GraphElementType> nodeOrEdgeOrRel;
    @XmlAttribute(name = "role")
    protected String role;
    @XmlAttribute(name = "edgeids")
    protected Boolean edgeids;
    @XmlAttribute(name = "hypergraph")
    protected Boolean hypergraph;
    @XmlAttribute(name = "edgemode")
    protected EdgemodeType edgemode;

    /**
     * Gets the value of the nodeOrEdgeOrRel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nodeOrEdgeOrRel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNodeOrEdgeOrRel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelType }
     * {@link NodeType }
     * {@link EdgeType }
     * 
     * 
     */
    public List<GraphElementType> getNodeOrEdgeOrRel() {
        if (nodeOrEdgeOrRel == null) {
            nodeOrEdgeOrRel = new ArrayList<GraphElementType>();
        }
        return this.nodeOrEdgeOrRel;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the edgeids property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEdgeids() {
        if (edgeids == null) {
            return false;
        } else {
            return edgeids;
        }
    }

    /**
     * Sets the value of the edgeids property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEdgeids(Boolean value) {
        this.edgeids = value;
    }

    /**
     * Gets the value of the hypergraph property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHypergraph() {
        if (hypergraph == null) {
            return false;
        } else {
            return hypergraph;
        }
    }

    /**
     * Sets the value of the hypergraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHypergraph(Boolean value) {
        this.hypergraph = value;
    }

    /**
     * Gets the value of the edgemode property.
     * 
     * @return
     *     possible object is
     *     {@link EdgemodeType }
     *     
     */
    public EdgemodeType getEdgemode() {
        if (edgemode == null) {
            return EdgemodeType.DIRECTED;
        } else {
            return edgemode;
        }
    }

    /**
     * Sets the value of the edgemode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdgemodeType }
     *     
     */
    public void setEdgemode(EdgemodeType value) {
        this.edgemode = value;
    }

}
