<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="shop" nsURI="http://groove.utwente.nl/ecore/shop" nsPrefix="shop">
  <eClassifiers xsi:type="ecore:EClass" name="Shop">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="open"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1"
        upperBound="-1" ordered="false" containment="true" eType="#//Item"
        eOpposite="#//Item/shop"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers" upperBound="-1"
        ordered="false" containment="true" eType="#//Customer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shop" lowerBound="1"
        eType="#//Shop" eOpposite="#//Shop/items"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isbn" eType="#//Isbn"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//catalog/Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="favourites" upperBound="-1"
        ordered="false" eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Category">
    <eLiterals name="UNKNOWN"/>
    <eLiterals name="FICTION" value="1"/>
    <eLiterals name="NONFICTION" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Isbn" instanceClassName="java.lang.String"/>
  <eSubpackages name="catalog" nsURI="http://groove.utwente.nl/ecore/shop/catalog"
      nsPrefix="catalog">
    <eClassifiers xsi:type="ecore:EClass" name="Item">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="label"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
