/*
 * GROOVE: GRaphs for Object Oriented VErification Copyright 2003--2023
 * University of Twente
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * $Id$
 */
package nl.utwente.groove.gui.view.cell;

import java.util.EnumSet;
import java.util.Set;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

import nl.utwente.groove.control.graph.ControlEdge;
import nl.utwente.groove.control.graph.ControlGraph;
import nl.utwente.groove.control.instance.Step;
import nl.utwente.groove.gui.look.Look;
import nl.utwente.groove.gui.view.GraphViewModel;
import nl.utwente.groove.util.HTMLConverter;
import nl.utwente.groove.util.Strings;

/**
 * Edge cell of a control graph, wrapping control edges.
 * @author Arend Rensink
 * @version $Revision$
 */
@NonNullByDefault
public class CtrlEdgeCell extends AViewEdge<ControlGraph> {
    /** Constructs an edge cell for a given view model. */
    public CtrlEdgeCell(GraphViewModel<ControlGraph> viewModel) {
        super(viewModel);
    }

    @Override
    public @Nullable ControlEdge getEdge() {
        return (ControlEdge) super.getEdge();
    }

    @Override
    protected StringBuilder getEdgeKindDescription() {
        return new StringBuilder("transition");
    }

    @Override
    protected String getLabelDescription() {
        StringBuffer result = new StringBuffer(", generated by ");
        String[] displayedLabels = new String[getEdges().size()];
        int labelIndex = 0;
        for (Object part : getEdges()) {
            Step trans = (Step) part;
            String description = trans.toString();
            displayedLabels[labelIndex] = HTMLConverter.STRONG_TAG.on(description, true);
            labelIndex++;
        }
        if (displayedLabels.length == 1) {
            result.append(displayedLabels[0]);
        } else {
            result.append(Strings.toString(displayedLabels, "<br>- ", "", "<br>- "));
        }
        return result.toString();
    }

    @Override
    protected Set<Look> getStructuralLooks() {
        var edge = getEdge();
        if (edge != null && edge.isVerdict()) {
            return EnumSet.of(Look.CTRL_VERDICT);
        } else {
            return EnumSet.of(Look.TRANS);
        }
    }
}
