/*
 * GROOVE: GRaphs for Object Oriented VErification Copyright 2003--2023
 * University of Twente
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * $Id$
 */
package nl.utwente.groove.gui.view.cell;

import java.util.EnumSet;
import java.util.Set;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

import nl.utwente.groove.graph.Edge;
import nl.utwente.groove.gui.look.Look;
import nl.utwente.groove.gui.look.VisualKey;
import nl.utwente.groove.gui.view.LTSGraphViewModel;
import nl.utwente.groove.gui.view.LTSViewEdge;
import nl.utwente.groove.lts.GTS;
import nl.utwente.groove.lts.GraphNextState;
import nl.utwente.groove.lts.GraphState;
import nl.utwente.groove.lts.GraphTransition;
import nl.utwente.groove.lts.RuleTransition;
import nl.utwente.groove.util.HTMLConverter;
import nl.utwente.groove.util.Strings;

/**
 * Edge cell of an LTS, wrapping graph transitions.
 * @author Arend Rensink
 * @version $Revision$
 */
@NonNullByDefault
public class LTSEdgeCell extends AViewEdge<GTS> implements LTSViewEdge {
    /** Constructs an edge cell for a given view model. */
    public LTSEdgeCell(LTSGraphViewModel viewModel) {
        super(viewModel);
    }

    @Override
    public LTSGraphViewModel getViewModel() {
        return (LTSGraphViewModel) super.getViewModel();
    }

    @Override
    public void initialise() {
        super.initialise();
        this.visibleFlag = true;
    }

    @Override
    public @Nullable LTSVertexCell getSourceVertex() {
        return (LTSVertexCell) super.getSourceVertex();
    }

    @Override
    public @Nullable LTSVertexCell getTargetVertex() {
        return (LTSVertexCell) super.getTargetVertex();
    }

    @Override
    public void setSource(@Nullable AViewVertex<GTS> vertex) {
        super.setSource(vertex);
        if (vertex != null) {
            ((LTSVertexCell) vertex).changeOutVisible(true, getEdges().size());
        }
    }

    @Override
    public void setTarget(@Nullable AViewVertex<GTS> vertex) {
        super.setTarget(vertex);
        if (vertex instanceof LTSVertexCell targetVertex) {
            GraphState target = targetVertex.getNode();
            if (target instanceof GraphNextState trans && getEdges().contains(trans)) {
                targetVertex.setParentEdge(this);
            }
        }
    }

    @Override
    public boolean isCompatible(Edge edge) {
        if (!super.isCompatible(edge)) {
            return false;
        }
        GraphTransition trans = (GraphTransition) edge;
        if (isInternal() != trans.isInnerStep()) {
            return false;
        }
        if (isAbsent() != (trans.source().isAbsent() || trans.target().isAbsent())) {
            return false;
        }
        return true;
    }

    @Override
    public void addEdge(Edge edge) {
        super.addEdge(edge);
        // updates the look on the basis of the edge
        setLook(Look.RECIPE, isInternal());
        setLook(Look.ABSENT, isAbsent());
        setLook(Look.RESULT, isResult());
        LTSVertexCell sourceVertex = getSourceVertex();
        if (sourceVertex != null && getVisuals().isVisible()) {
            sourceVertex.changeOutVisible(true, 1);
        }
    }

    @Override
    public @Nullable GraphTransition getEdge() {
        return (GraphTransition) super.getEdge();
    }

    /** Returns the first transition of this cell; fails if there is none. */
    private GraphTransition getTransition() {
        var result = getEdge();
        assert result != null; // the cell wraps at least one transition when queried
        return result;
    }

    @SuppressWarnings("unchecked")
    @Override
    public Set<? extends GraphTransition> getEdges() {
        return (Set<? extends GraphTransition>) super.getEdges();
    }

    @Override
    protected StringBuilder getEdgeKindDescription() {
        return new StringBuilder("transition");
    }

    @Override
    protected String getLabelDescription() {
        StringBuffer result = new StringBuffer(", generated by ");
        String[] displayedLabels = new String[getEdges().size()];
        int labelIndex = 0;
        boolean showAnchors = getViewModel().getController().isShowAnchors();
        for (Object part : getEdges()) {
            RuleTransition trans = (RuleTransition) part;
            String description;
            if (showAnchors) {
                description = trans.getEvent().toString();
            } else {
                description = trans.getEvent().getAction().getQualName().toString();
            }
            displayedLabels[labelIndex] = HTMLConverter.STRONG_TAG.on(description, true);
            labelIndex++;
        }
        if (displayedLabels.length == 1) {
            result.append(displayedLabels[0]);
        } else {
            result.append(Strings.toString(displayedLabels, "<br>- ", "", "<br>- "));
        }
        return result.toString();
    }

    /** Indicates if this transition is currently active. */
    final boolean isActive() {
        return getLooks().contains(Look.ACTIVE);
    }

    /** Indicates if the source or target state of the transition is absent. */
    final boolean isAbsent() {
        var trans = getTransition();
        return trans.source().isAbsent() || trans.target().isAbsent();
    }

    /** Indicates if the transition is an inner step of a recipe. */
    final boolean isInternal() {
        return getTransition().isInnerStep();
    }

    /** Indicates if any of the transitions is part of the current exploration result. */
    boolean isResult() {
        var controller = getViewModel().getController();
        return getEdges().stream().anyMatch(controller::isResult);
    }

    @Override
    public boolean setVisibleFlag(boolean visible) {
        boolean result = this.visibleFlag != visible;
        if (result) {
            boolean oldVisible = getVisuals().isVisible();
            this.visibleFlag = visible;
            if (visible != oldVisible) {
                setStale(VisualKey.VISIBLE);
                LTSVertexCell sourceVertex = getSourceVertex();
                if (sourceVertex != null && visible == getVisuals().isVisible()) {
                    sourceVertex.changeOutVisible(visible, getEdges().size());
                }
            }
        }
        return result;
    }

    @Override
    public boolean hasVisibleFlag() {
        return this.visibleFlag;
    }

    @Override
    public final boolean setActive(boolean active) {
        return setLook(Look.ACTIVE, active);
    }

    @Override
    protected Set<Look> getStructuralLooks() {
        return EnumSet.of(Look.TRANS);
    }

    /** Flag indicating that this transition is set to be visible. */
    private boolean visibleFlag;
}
