//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.25 at 01:59:43 AM CEST 
//


package de.gupro.gxl.gxl_1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for edgemodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="edgemodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="directed"/>
 *     &lt;enumeration value="undirected"/>
 *     &lt;enumeration value="defaultdirected"/>
 *     &lt;enumeration value="defaultundirected"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "edgemodeType")
@XmlEnum
public enum EdgemodeType {

    @XmlEnumValue("directed")
    DIRECTED("directed"),
    @XmlEnumValue("undirected")
    UNDIRECTED("undirected"),
    @XmlEnumValue("defaultdirected")
    DEFAULTDIRECTED("defaultdirected"),
    @XmlEnumValue("defaultundirected")
    DEFAULTUNDIRECTED("defaultundirected");
    private final String value;

    EdgemodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EdgemodeType fromValue(String v) {
        for (EdgemodeType c: EdgemodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
