//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.25 at 01:59:43 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gupro.de/GXL/gxl-1.0.dtd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.gupro.gxl.gxl_1_0;
