//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.07.20 at 10:15:31 AM CEST
//

package nl.utwente.groove.io.conceptual.configuration.schema;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for indexType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="indexType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="useIntermediate"/>
 *     &lt;enumeration value="preferValue"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "indexType")
@XmlEnum
@SuppressWarnings("javadoc")
public enum IndexType {
    @XmlEnumValue("useIntermediate")
    USE_INTERMEDIATE("useIntermediate"),
    @XmlEnumValue("preferValue")
    PREFER_VALUE("preferValue");

    private final String value;

    IndexType(String v) {
        this.value = v;
    }

    public String value() {
        return this.value;
    }
}
