//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.16 at 12:06:26 PM CET 
//


package groove.io.conceptual.configuration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sourceLocation" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element name="typeModel" type="{ConfigSchema}typeModel"/&gt;
 *         &lt;element name="instanceModel" type="{ConfigSchema}instanceModel"/&gt;
 *         &lt;element name="global" type="{ConfigSchema}global"/&gt;
 *         &lt;element name="meta" type="{ConfigSchema}meta"/&gt;
 *         &lt;element name="constraints" type="{ConfigSchema}constraints"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceLocation",
    "typeModel",
    "instanceModel",
    "global",
    "meta",
    "constraints"
})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String sourceLocation;
    @XmlElement(required = true)
    protected TypeModel typeModel;
    @XmlElement(required = true)
    protected InstanceModel instanceModel;
    @XmlElement(required = true)
    protected Global global;
    @XmlElement(required = true)
    protected Meta meta;
    @XmlElement(required = true)
    protected Constraints constraints;

    /**
     * Gets the value of the sourceLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceLocation() {
        return sourceLocation;
    }

    /**
     * Sets the value of the sourceLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceLocation(String value) {
        this.sourceLocation = value;
    }

    /**
     * Gets the value of the typeModel property.
     * 
     * @return
     *     possible object is
     *     {@link TypeModel }
     *     
     */
    public TypeModel getTypeModel() {
        return typeModel;
    }

    /**
     * Sets the value of the typeModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeModel }
     *     
     */
    public void setTypeModel(TypeModel value) {
        this.typeModel = value;
    }

    /**
     * Gets the value of the instanceModel property.
     * 
     * @return
     *     possible object is
     *     {@link InstanceModel }
     *     
     */
    public InstanceModel getInstanceModel() {
        return instanceModel;
    }

    /**
     * Sets the value of the instanceModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstanceModel }
     *     
     */
    public void setInstanceModel(InstanceModel value) {
        this.instanceModel = value;
    }

    /**
     * Gets the value of the global property.
     * 
     * @return
     *     possible object is
     *     {@link Global }
     *     
     */
    public Global getGlobal() {
        return global;
    }

    /**
     * Sets the value of the global property.
     * 
     * @param value
     *     allowed object is
     *     {@link Global }
     *     
     */
    public void setGlobal(Global value) {
        this.global = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link Meta }
     *     
     */
    public Meta getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta }
     *     
     */
    public void setMeta(Meta value) {
        this.meta = value;
    }

    /**
     * Gets the value of the constraints property.
     * 
     * @return
     *     possible object is
     *     {@link Constraints }
     *     
     */
    public Constraints getConstraints() {
        return constraints;
    }

    /**
     * Sets the value of the constraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Constraints }
     *     
     */
    public void setConstraints(Constraints value) {
        this.constraints = value;
    }

}
