//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.05 at 10:44:15 AM CET 
//


package groove.io.conceptual.configuration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="typeModel" type="{ConfigSchema}typeModel"/&gt;
 *         &lt;element name="instanceModel" type="{ConfigSchema}instanceModel"/&gt;
 *         &lt;element name="global" type="{ConfigSchema}global"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "typeModel",
    "instanceModel",
    "global"
})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(required = true)
    protected TypeModel typeModel;
    @XmlElement(required = true)
    protected InstanceModel instanceModel;
    @XmlElement(required = true)
    protected Global global;

    /**
     * Gets the value of the typeModel property.
     * 
     * @return
     *     possible object is
     *     {@link TypeModel }
     *     
     */
    public TypeModel getTypeModel() {
        return typeModel;
    }

    /**
     * Sets the value of the typeModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeModel }
     *     
     */
    public void setTypeModel(TypeModel value) {
        this.typeModel = value;
    }

    /**
     * Gets the value of the instanceModel property.
     * 
     * @return
     *     possible object is
     *     {@link InstanceModel }
     *     
     */
    public InstanceModel getInstanceModel() {
        return instanceModel;
    }

    /**
     * Sets the value of the instanceModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstanceModel }
     *     
     */
    public void setInstanceModel(InstanceModel value) {
        this.instanceModel = value;
    }

    /**
     * Gets the value of the global property.
     * 
     * @return
     *     possible object is
     *     {@link Global }
     *     
     */
    public Global getGlobal() {
        return global;
    }

    /**
     * Sets the value of the global property.
     * 
     * @param value
     *     allowed object is
     *     {@link Global }
     *     
     */
    public void setGlobal(Global value) {
        this.global = value;
    }

}
