//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.16 at 12:06:26 PM CET 
//


package groove.io.conceptual.configuration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for constraints complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="constraints"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rules"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="setDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="checks"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="checkUniqueness" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *                 &lt;attribute name="checkIdentifier" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *                 &lt;attribute name="checkKeyset" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *                 &lt;attribute name="checkOpposite" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *                 &lt;attribute name="checkOrdering" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *                 &lt;attribute name="checkEnum" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "constraints", propOrder = {
    "rules",
    "checks"
})
public class Constraints {

    @XmlElement(required = true)
    protected Constraints.Rules rules;
    @XmlElement(required = true)
    protected Constraints.Checks checks;

    /**
     * Gets the value of the rules property.
     * 
     * @return
     *     possible object is
     *     {@link Constraints.Rules }
     *     
     */
    public Constraints.Rules getRules() {
        return rules;
    }

    /**
     * Sets the value of the rules property.
     * 
     * @param value
     *     allowed object is
     *     {@link Constraints.Rules }
     *     
     */
    public void setRules(Constraints.Rules value) {
        this.rules = value;
    }

    /**
     * Gets the value of the checks property.
     * 
     * @return
     *     possible object is
     *     {@link Constraints.Checks }
     *     
     */
    public Constraints.Checks getChecks() {
        return checks;
    }

    /**
     * Sets the value of the checks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Constraints.Checks }
     *     
     */
    public void setChecks(Constraints.Checks value) {
        this.checks = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="checkUniqueness" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
     *       &lt;attribute name="checkIdentifier" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
     *       &lt;attribute name="checkKeyset" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
     *       &lt;attribute name="checkOpposite" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
     *       &lt;attribute name="checkOrdering" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
     *       &lt;attribute name="checkEnum" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Checks {

        @XmlAttribute(name = "checkUniqueness")
        protected Boolean checkUniqueness;
        @XmlAttribute(name = "checkIdentifier")
        protected Boolean checkIdentifier;
        @XmlAttribute(name = "checkKeyset")
        protected Boolean checkKeyset;
        @XmlAttribute(name = "checkOpposite")
        protected Boolean checkOpposite;
        @XmlAttribute(name = "checkOrdering")
        protected Boolean checkOrdering;
        @XmlAttribute(name = "checkEnum")
        protected Boolean checkEnum;

        /**
         * Gets the value of the checkUniqueness property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCheckUniqueness() {
            if (checkUniqueness == null) {
                return true;
            } else {
                return checkUniqueness;
            }
        }

        /**
         * Sets the value of the checkUniqueness property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCheckUniqueness(Boolean value) {
            this.checkUniqueness = value;
        }

        /**
         * Gets the value of the checkIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCheckIdentifier() {
            if (checkIdentifier == null) {
                return true;
            } else {
                return checkIdentifier;
            }
        }

        /**
         * Sets the value of the checkIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCheckIdentifier(Boolean value) {
            this.checkIdentifier = value;
        }

        /**
         * Gets the value of the checkKeyset property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCheckKeyset() {
            if (checkKeyset == null) {
                return true;
            } else {
                return checkKeyset;
            }
        }

        /**
         * Sets the value of the checkKeyset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCheckKeyset(Boolean value) {
            this.checkKeyset = value;
        }

        /**
         * Gets the value of the checkOpposite property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCheckOpposite() {
            if (checkOpposite == null) {
                return true;
            } else {
                return checkOpposite;
            }
        }

        /**
         * Sets the value of the checkOpposite property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCheckOpposite(Boolean value) {
            this.checkOpposite = value;
        }

        /**
         * Gets the value of the checkOrdering property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCheckOrdering() {
            if (checkOrdering == null) {
                return true;
            } else {
                return checkOrdering;
            }
        }

        /**
         * Sets the value of the checkOrdering property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCheckOrdering(Boolean value) {
            this.checkOrdering = value;
        }

        /**
         * Gets the value of the checkEnum property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCheckEnum() {
            if (checkEnum == null) {
                return true;
            } else {
                return checkEnum;
            }
        }

        /**
         * Sets the value of the checkEnum property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCheckEnum(Boolean value) {
            this.checkEnum = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="setDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Rules {

        @XmlAttribute(name = "setDefault")
        protected Boolean setDefault;

        /**
         * Gets the value of the setDefault property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isSetDefault() {
            if (setDefault == null) {
                return true;
            } else {
                return setDefault;
            }
        }

        /**
         * Sets the value of the setDefault property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSetDefault(Boolean value) {
            this.setDefault = value;
        }

    }

}
