//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.16 at 12:06:26 PM CET 
//


package groove.io.conceptual.configuration.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for global complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="global"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id_overrides" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="strings" type="{ConfigSchema}stringsType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="nullable" type="{ConfigSchema}nullableType" default="required" /&gt;
 *       &lt;attribute name="id_mode" type="{ConfigSchema}idModeType" default="disambiguate" /&gt;
 *       &lt;attribute name="id_separator" type="{ConfigSchema}idSeparatorType" default="$" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "global", propOrder = {
    "idOverrides",
    "strings"
})
public class Global {

    @XmlElement(name = "id_overrides")
    protected List<Global.IdOverrides> idOverrides;
    @XmlElement(required = true)
    protected StringsType strings;
    @XmlAttribute(name = "nullable")
    protected NullableType nullable;
    @XmlAttribute(name = "id_mode")
    protected IdModeType idMode;
    @XmlAttribute(name = "id_separator")
    protected String idSeparator;

    /**
     * Gets the value of the idOverrides property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idOverrides property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdOverrides().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Global.IdOverrides }
     * 
     * 
     */
    public List<Global.IdOverrides> getIdOverrides() {
        if (idOverrides == null) {
            idOverrides = new ArrayList<Global.IdOverrides>();
        }
        return this.idOverrides;
    }

    /**
     * Gets the value of the strings property.
     * 
     * @return
     *     possible object is
     *     {@link StringsType }
     *     
     */
    public StringsType getStrings() {
        return strings;
    }

    /**
     * Sets the value of the strings property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringsType }
     *     
     */
    public void setStrings(StringsType value) {
        this.strings = value;
    }

    /**
     * Gets the value of the nullable property.
     * 
     * @return
     *     possible object is
     *     {@link NullableType }
     *     
     */
    public NullableType getNullable() {
        if (nullable == null) {
            return NullableType.REQUIRED;
        } else {
            return nullable;
        }
    }

    /**
     * Sets the value of the nullable property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullableType }
     *     
     */
    public void setNullable(NullableType value) {
        this.nullable = value;
    }

    /**
     * Gets the value of the idMode property.
     * 
     * @return
     *     possible object is
     *     {@link IdModeType }
     *     
     */
    public IdModeType getIdMode() {
        if (idMode == null) {
            return IdModeType.DISAMBIGUATE;
        } else {
            return idMode;
        }
    }

    /**
     * Sets the value of the idMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdModeType }
     *     
     */
    public void setIdMode(IdModeType value) {
        this.idMode = value;
    }

    /**
     * Gets the value of the idSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSeparator() {
        if (idSeparator == null) {
            return "$";
        } else {
            return idSeparator;
        }
    }

    /**
     * Sets the value of the idSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSeparator(String value) {
        this.idSeparator = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name"
    })
    public static class IdOverrides {

        @XmlElement(required = true)
        protected String id;
        @XmlElement(required = true)
        protected String name;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
