//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.05 at 10:44:15 AM CET 
//


package groove.io.conceptual.configuration.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for graphType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="graphType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="typeGraph"/&gt;
 *     &lt;enumeration value="ruleGraph"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "graphType")
@XmlEnum
public enum GraphType {

    @XmlEnumValue("typeGraph")
    TYPE_GRAPH("typeGraph"),
    @XmlEnumValue("ruleGraph")
    RULE_GRAPH("ruleGraph");
    private final String value;

    GraphType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GraphType fromValue(String v) {
        for (GraphType c: GraphType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
