//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.16 at 12:06:26 PM CET 
//


package groove.io.conceptual.configuration.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for idModeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="idModeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="full"/&gt;
 *     &lt;enumeration value="flat"/&gt;
 *     &lt;enumeration value="disambiguate"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "idModeType")
@XmlEnum
public enum IdModeType {

    @XmlEnumValue("full")
    FULL("full"),
    @XmlEnumValue("flat")
    FLAT("flat"),
    @XmlEnumValue("disambiguate")
    DISAMBIGUATE("disambiguate");
    private final String value;

    IdModeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IdModeType fromValue(String v) {
        for (IdModeType c: IdModeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
