//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.05 at 10:44:15 AM CET 
//


package groove.io.conceptual.configuration.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for intermediateNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="intermediateNameType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="field"/&gt;
 *     &lt;enumeration value="type"/&gt;
 *     &lt;enumeration value="combined"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "intermediateNameType")
@XmlEnum
public enum IntermediateNameType {

    @XmlEnumValue("field")
    FIELD("field"),
    @XmlEnumValue("type")
    TYPE("type"),
    @XmlEnumValue("combined")
    COMBINED("combined");
    private final String value;

    IntermediateNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IntermediateNameType fromValue(String v) {
        for (IntermediateNameType c: IntermediateNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
