//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.16 at 12:06:26 PM CET 
//


package groove.io.conceptual.configuration.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for literalsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="literalsType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="singleton"/&gt;
 *     &lt;enumeration value="multiple"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "literalsType")
@XmlEnum
public enum LiteralsType {

    @XmlEnumValue("singleton")
    SINGLETON("singleton"),
    @XmlEnumValue("multiple")
    MULTIPLE("multiple");
    private final String value;

    LiteralsType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LiteralsType fromValue(String v) {
        for (LiteralsType c: LiteralsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
