//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.16 at 12:06:26 PM CET 
//


package groove.io.conceptual.configuration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for meta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="meta"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="metaSchema" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="metaType" type="{http://www.w3.org/2001/XMLSchema}string" default="Type" /&gt;
 *       &lt;attribute name="metaClass" type="{http://www.w3.org/2001/XMLSchema}string" default="Class" /&gt;
 *       &lt;attribute name="metaClassNullable" type="{http://www.w3.org/2001/XMLSchema}string" default="NullableClass" /&gt;
 *       &lt;attribute name="metaEnum" type="{http://www.w3.org/2001/XMLSchema}string" default="Enum" /&gt;
 *       &lt;attribute name="metaTuple" type="{http://www.w3.org/2001/XMLSchema}string" default="Tuple" /&gt;
 *       &lt;attribute name="metaContainerBag" type="{http://www.w3.org/2001/XMLSchema}string" default="Bag" /&gt;
 *       &lt;attribute name="metaContainerSet" type="{http://www.w3.org/2001/XMLSchema}string" default="Set" /&gt;
 *       &lt;attribute name="metaContainerSeq" type="{http://www.w3.org/2001/XMLSchema}string" default="Seq" /&gt;
 *       &lt;attribute name="metaContainerOrd" type="{http://www.w3.org/2001/XMLSchema}string" default="Ord" /&gt;
 *       &lt;attribute name="metaDataType" type="{http://www.w3.org/2001/XMLSchema}string" default="DataType" /&gt;
 *       &lt;attribute name="metaIntermediate" type="{http://www.w3.org/2001/XMLSchema}string" default="Intermediate" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "meta")
public class Meta {

    @XmlAttribute(name = "metaSchema")
    protected Boolean metaSchema;
    @XmlAttribute(name = "metaType")
    protected String metaType;
    @XmlAttribute(name = "metaClass")
    protected String metaClass;
    @XmlAttribute(name = "metaClassNullable")
    protected String metaClassNullable;
    @XmlAttribute(name = "metaEnum")
    protected String metaEnum;
    @XmlAttribute(name = "metaTuple")
    protected String metaTuple;
    @XmlAttribute(name = "metaContainerBag")
    protected String metaContainerBag;
    @XmlAttribute(name = "metaContainerSet")
    protected String metaContainerSet;
    @XmlAttribute(name = "metaContainerSeq")
    protected String metaContainerSeq;
    @XmlAttribute(name = "metaContainerOrd")
    protected String metaContainerOrd;
    @XmlAttribute(name = "metaDataType")
    protected String metaDataType;
    @XmlAttribute(name = "metaIntermediate")
    protected String metaIntermediate;

    /**
     * Gets the value of the metaSchema property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMetaSchema() {
        if (metaSchema == null) {
            return false;
        } else {
            return metaSchema;
        }
    }

    /**
     * Sets the value of the metaSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMetaSchema(Boolean value) {
        this.metaSchema = value;
    }

    /**
     * Gets the value of the metaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaType() {
        if (metaType == null) {
            return "Type";
        } else {
            return metaType;
        }
    }

    /**
     * Sets the value of the metaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaType(String value) {
        this.metaType = value;
    }

    /**
     * Gets the value of the metaClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaClass() {
        if (metaClass == null) {
            return "Class";
        } else {
            return metaClass;
        }
    }

    /**
     * Sets the value of the metaClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaClass(String value) {
        this.metaClass = value;
    }

    /**
     * Gets the value of the metaClassNullable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaClassNullable() {
        if (metaClassNullable == null) {
            return "NullableClass";
        } else {
            return metaClassNullable;
        }
    }

    /**
     * Sets the value of the metaClassNullable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaClassNullable(String value) {
        this.metaClassNullable = value;
    }

    /**
     * Gets the value of the metaEnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaEnum() {
        if (metaEnum == null) {
            return "Enum";
        } else {
            return metaEnum;
        }
    }

    /**
     * Sets the value of the metaEnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaEnum(String value) {
        this.metaEnum = value;
    }

    /**
     * Gets the value of the metaTuple property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaTuple() {
        if (metaTuple == null) {
            return "Tuple";
        } else {
            return metaTuple;
        }
    }

    /**
     * Sets the value of the metaTuple property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaTuple(String value) {
        this.metaTuple = value;
    }

    /**
     * Gets the value of the metaContainerBag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaContainerBag() {
        if (metaContainerBag == null) {
            return "Bag";
        } else {
            return metaContainerBag;
        }
    }

    /**
     * Sets the value of the metaContainerBag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaContainerBag(String value) {
        this.metaContainerBag = value;
    }

    /**
     * Gets the value of the metaContainerSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaContainerSet() {
        if (metaContainerSet == null) {
            return "Set";
        } else {
            return metaContainerSet;
        }
    }

    /**
     * Sets the value of the metaContainerSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaContainerSet(String value) {
        this.metaContainerSet = value;
    }

    /**
     * Gets the value of the metaContainerSeq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaContainerSeq() {
        if (metaContainerSeq == null) {
            return "Seq";
        } else {
            return metaContainerSeq;
        }
    }

    /**
     * Sets the value of the metaContainerSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaContainerSeq(String value) {
        this.metaContainerSeq = value;
    }

    /**
     * Gets the value of the metaContainerOrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaContainerOrd() {
        if (metaContainerOrd == null) {
            return "Ord";
        } else {
            return metaContainerOrd;
        }
    }

    /**
     * Sets the value of the metaContainerOrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaContainerOrd(String value) {
        this.metaContainerOrd = value;
    }

    /**
     * Gets the value of the metaDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaDataType() {
        if (metaDataType == null) {
            return "DataType";
        } else {
            return metaDataType;
        }
    }

    /**
     * Sets the value of the metaDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaDataType(String value) {
        this.metaDataType = value;
    }

    /**
     * Gets the value of the metaIntermediate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaIntermediate() {
        if (metaIntermediate == null) {
            return "Intermediate";
        } else {
            return metaIntermediate;
        }
    }

    /**
     * Sets the value of the metaIntermediate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaIntermediate(String value) {
        this.metaIntermediate = value;
    }

}
