//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.16 at 12:06:26 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "ConfigSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package groove.io.conceptual.configuration.schema;
