#! /bin/sh

# sets GROOVE environment variables to default values
# if they have not yet been set

GROOVE_SRC=`dirname $0`
if [ $GROOVE_SRC = "." ];
then
  GROOVE_HOME=.
else
  GROOVE_HOME=`dirname $GROOVE_SRC`
fi

if [ "X"$GROOVE_JAR_DIR = "X" ];
then
    GROOVE_JAR_DIR=${GROOVE_HOME}/lib;
    export GROOVE_JAR_DIR;
fi
if [ "X"$GROOVE_CLASS_DIR = "X" ]; 
then
    GROOVE_CLASS_DIR=${GROOVE_HOME}/classes;
    export GROOVE_CLASS_DIR;
fi
if [ "X"$GROOVE_DOC_DIR = "X" ]; 
then
    GROOVE_DOC_DIR=${GROOVE_HOME}/doc;
    export GROOVE_DOC_DIR;
fi
if [ "X"$GROOVE_RESOURCE_DIR = "X" ]; 
then
    GROOVE_RESOURCE_DIR=${GROOVE_HOME}/resources;
    export GROOVE_RESOURCE_DIR;
fi

if [ "X"$JAVA_HOME = "X" ];
then
    JAVA_HOME=`which javac`
    JAVA_HOME=`dirname ${JAVA_HOME}`
    JAVA_HOME=`dirname ${JAVA_HOME}`
fi

# echo defaults GROOVE_CLASS_DIR: $GROOVE_CLASS_DIR
