#! /bin/sh

. `dirname $0`/defaults

# turn jar files in GROOVE_JAR_DIR into :-separated list
JARS=`echo \`ls ${GROOVE_JAR_DIR}/*.jar\` | sed 's/  */:/g'`

# main class = groove.gui class named by invocation of Run
${JAVA_HOME}/bin/java \
    -classpath ${JARS}:${GROOVE_CLASS_DIR}:${GROOVE_RESOURCE_DIR} \
    groove.gui.`basename $0` $@
