/*
 * RuleApplOptionsPanel.java
 *
 * Created on June 6, 2008, 11:21 AM
 */

package groove.gui.chscenar;

import groove.trans.Rule;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author  io
 */
public class RuleApplOptionsPanel extends javax.swing.JPanel
            implements ExploreConditionOptionsProvider<Rule> {

    /** Creates new form RuleApplOptionsPanel */
    public RuleApplOptionsPanel(Rule[] rules) {
        setRules(rules);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel l1 = new javax.swing.JLabel();
        rulesComboBox = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));
        setPreferredSize(new java.awt.Dimension(400, 100));

        l1.setLabelFor(rulesComboBox);
        l1.setText("Select a rule");

        rulesComboBox.setModel(new DefaultComboBoxModel(getRules()));
        rulesComboBox.setRenderer(new RuleCellRenderer());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rulesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(rulesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox rulesComboBox;
    // End of variables declaration//GEN-END:variables

    
    // ----------------------------------------------------------------------
    // PUBLIC METHODS
    // ----------------------------------------------------------------------
    private Rule[] rules;
    
    private void setRules (Rule[] rules) {
        this.rules = rules;
    }
    private Rule[] getRules () {
        return rules;
    }
    
    private Rule getSelectedRule() {
        return (Rule) rulesComboBox.getSelectedItem();
    }

    public Rule getOptions() {
        return getSelectedRule();
    }
    
    // ----------------------------------------------------------------------
    // HELPER METHODS
    // ----------------------------------------------------------------------
    
}
